### ISSUE TITLE
TagBot does not work when release commit is not in master branch

### ISSUE THREAD

**Issue by tkf** [JuliaRegistries/TagBot#73]
I noticed that a release I made via https://github.com/tkf/Transducers.jl/issues/233 is not tagged by TagBot. It's been failing with

```
No matching commit was found for version v0.4.20 (c4f4cbdb7023e09acd0faebca628d386f1aaab98)
```

e.g. https://github.com/tkf/Transducers.jl/actions/runs/45228286

However, as you can see in https://github.com/JuliaRegistries/General/pull/10043, the related commit is `bf3a4db8ec49754e0a841db90e95a16d635a8667`.  I'm not sure where `c4f4cbdb7023e09acd0faebca628d386f1aaab98` is comming from.  It does not exist in the repository https://github.com/tkf/Transducers.jl/commit/c4f4cbdb7023e09acd0faebca628d386f1aaab98 (shows 404).

I used `register(branch=release)` when invoking JuliaRegistrator. Can it be relevant?

**Comment by tkf** [comment]
Another example:
https://github.com/tkf/BenchmarkCI.jl/issues/42
https://github.com/JuliaRegistries/General/pull/10096
https://github.com/tkf/BenchmarkCI.jl/actions/runs/45227753

**Comment by tkf** [comment]
I tried running TagBot 1.6.1 and 1.6.0 but it didn't work: https://github.com/tkf/Transducers.jl/pull/234

It's strange because I think I made releases with those TagBot versions:
https://github.com/tkf/Transducers.jl/releases/tag/v0.4.19
https://github.com/tkf/Transducers.jl/releases/tag/v0.4.18

**Comment by tkf** [comment]
TagBot successfully tagged the release when I pushed the release commit to the `master` branch:

https://github.com/tkf/Transducers.jl/releases/tag/v0.4.20
https://github.com/tkf/BenchmarkCI.jl/releases/tag/v0.1.1

Can TagBot pull all git references when looking for the release commit?

**Comment by christopher-dG** [comment]
Ahhhhhh this is a side effect of #64 that did not occur to me. Before that PR, we used a Git command to view all commits on all branches and look for one that had the given tree SHA (`c4f4cbdb7023e09acd0faebca628d386f1aaab98` in your case). I don't think we can reasonably replicate the correct behaviour with the API, so part of that PR will have to get reverted. Thanks for reporting! I'll take care of it tonight.

**Comment by tkf** [comment]
I see. Thanks a lot for quickly looking into it!

**Comment by christopher-dG** [comment]
Oh yeah, I meant to mention about the "it used to work with other versions" thing:

Currently the version of TagBot that you use doesn't really matter, you still get the `tagbot:1` Docker image which is constantly updated with each release, so you're always running the latest code even if you don't want to. This will no longer be the case when #69 is merged.

**Comment by tkf** [comment]
Ah, I see. Thanks for the explanation and the fix!
